// <auto-generated />
using System;
using EFTestingWithSql.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFTestingWithSql.Data.Migrations
{
    [DbContext(typeof(WeatherContext))]
    partial class WeatherContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFTestingWithSql.Data.Models.Forecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sumary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Forecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2023, 1, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Cool",
                            TemperatureC = 14
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2023, 1, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Chilly",
                            TemperatureC = 8
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2023, 1, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Balmy",
                            TemperatureC = 8
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Chilly",
                            TemperatureC = 3
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2023, 1, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Warm",
                            TemperatureC = 16
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2023, 1, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Mild",
                            TemperatureC = 14
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Sweltering",
                            TemperatureC = 3
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2023, 1, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Warm",
                            TemperatureC = 22
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Scorching",
                            TemperatureC = 28
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Balmy",
                            TemperatureC = 2
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Sweltering",
                            TemperatureC = 2
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Bracing",
                            TemperatureC = 28
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Freezing",
                            TemperatureC = 22
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Scorching",
                            TemperatureC = 22
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2022, 12, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Scorching",
                            TemperatureC = 14
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2022, 12, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Sweltering",
                            TemperatureC = 9
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2022, 12, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Hot",
                            TemperatureC = 9
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2022, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Hot",
                            TemperatureC = 0
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2022, 12, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Freezing",
                            TemperatureC = 17
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Warm",
                            TemperatureC = 1
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2022, 12, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Balmy",
                            TemperatureC = 0
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2022, 12, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Freezing",
                            TemperatureC = 15
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2022, 12, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Bracing",
                            TemperatureC = 15
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTime(2022, 12, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Mild",
                            TemperatureC = 26
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTime(2022, 12, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Mild",
                            TemperatureC = 25
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateTime(2022, 12, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Mild",
                            TemperatureC = 8
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateTime(2022, 12, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Freezing",
                            TemperatureC = 17
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateTime(2022, 12, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Balmy",
                            TemperatureC = 17
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateTime(2022, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Bracing",
                            TemperatureC = 12
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateTime(2022, 12, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Sumary = "Chilly",
                            TemperatureC = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
